### ISSUE TITLE
Version 3 gateway

### ISSUE THREAD

**Issue by Merlin83b** [cflurin/xiaomi-mqtt#14]
I've recently bought a "version 3" gateway, the type that has a USB socket for power rather than plugging stright into the wall.  I'm running xiaomi-mqtt and see the start "xiaomi-mqtt started." message but nothing after that.  On using tcpdump, I don't see any multicast messages coming out of the gateway, but instead see a broadcast every 90 seconds to port 54321 with 32 bytes in a UDP packet.

I see that this version was [mentioned in another thread](https://github.com/cflurin/xiaomi-mqtt/issues/10#issuecomment-440978192) and wonder if you might have a working theory as to how to proceed?  I'm more than happy to provide further debug info if you can tell me what's needed.

Attached is a pcap of the packets coming out of the gateway every 30 seconds.

[xg.zip](https://github.com/cflurin/xiaomi-mqtt/files/4504394/xg.zip)

**Comment by cflurin** [comment]
Hi,
I'm still using one gateway (version 2) for a few devices but I've moved to zigbee2mqtt for most of my devices (approy. 30).

So I don't see any advantages for the future.
Feel free to fork this project and modify it for your requaraments.

**Comment by Merlin83b** [comment]
Thanks, I've ordered a USB device for that so will give it a go.

**Comment by cflurin** [comment]
FYI I'm using the adapter  `CC2531` with antenna and one router `CC2530 + CC2591`
