### ISSUE TITLE
settings for Xiaomi-mqtt

### ISSUE THREAD

**Issue by muzixiaosanshi** [cflurin/xiaomi-mqtt#15]
Dear cflurin:
Thanks  for your contribution for this xiaomi-mqtt bridge.I have already downloaded and installed it.But I have One question about setting:
{
  "xiaomi": {
    "serverPort": 9898,
    "multicastAddress": "224.0.0.50",
    "multicastPort": 4321,
    "password": "FFF..."
  },
where can I get multicast address and multicast port ? where can i get password?
thanks for your help and reply in avance ,Thanks.

**Comment by cflurin** [comment]
The multicastAddress is the default "224.0.0.50"

To get the password you have to activate the developer mode in the Mi home app (android or iOS):

Have a look here:

https://www.domoticz.com/wiki/Xiaomi_Gateway_(Aqara)#Adding_the_Xiaomi_Gateway_to_Domoticz

or search for Mi home app developer mode on the internet.

**Comment by muzixiaosanshi** [comment]
> The multicastAddress is the default "224.0.0.50"
> 
> To get the password you have to activate the developer mode in the Mi home app (android or iOS):
> 
> Have a look here:
> 
> https://www.domoticz.com/wiki/Xiaomi_Gateway_(Aqara)#Adding_the_Xiaomi_Gateway_to_Domoticz
> 
> or search for Mi home app developer mode on the internet.

**Comment by muzixiaosanshi** [comment]
Hello cflurin:
Thanks for your quickly reply,  and I run xiaomi-mqtt ,it has below error:
![image](https://user-images.githubusercontent.com/18609558/106985383-513a3a00-67a4-11eb-8f87-c15ded71e15d.png)
and I use APP open local control as you mentioned above.
Do you know what is wrong for my case ?
Below is my config seeting:
![image](https://user-images.githubusercontent.com/18609558/106985560-a5ddb500-67a4-11eb-9c81-656011a50ddf.png)
Thx.

**Comment by cflurin** [comment]
Please, google, You'll find the solution.

**Comment by muzixiaosanshi** [comment]
Hello Cflurin,Thanks I google and solve above problem and come across a new question:
![image](https://user-images.githubusercontent.com/18609558/107375912-3a893f80-6b24-11eb-8eba-35d565d37785.png)
I found by google and could not find solution.
Do you know what's the reason?Thanks.
