### ISSUE TITLE
model: "ctrl_neutral1"

### ISSUE THREAD

**Issue by iChUdY** [cflurin/xiaomi-mqtt#4]
Hi,

my wall switch on topic xiaomi/from:
{
 "cmd":"read_ack",
 "model":"ctrl_neutral1",
 "sid":"158d0001828xxx",
 "short_id":30115,
 "data":{
      "voltage":3300,
       "channel_0":"off"
            }
}

I will try control this device to xiaomi/to/write by:
{"cmd":"write","model":"ctrl_neutral1","sid":"158d0001828xxx","short_id":30115,"data":{"channel_0":"on"}}

and always return msg:
"{"cmd":"xm","msg":"invalid JSON format >[object Object]<"}"

Control gateway LED by this metod works fine:
{"cmd":"write","model":"gateway","sid":"7811dcaf3xxx","data":{"rgb":"ffff0000"}}

**Comment by cflurin** [comment]
Hi,
I don't own this device but I tried to implement the `write-cmd`. Please install the latest version 0.3.5 and let me know whether it works.

**Comment by iChUdY** [comment]
Great. Now works fine 👌🏻

Thx

{"cmd":"write","model":"ctrl_neutral1","sid":"158d0001828xxx","short_id":30115,"data":{"channel_0":"on"}}

{"cmd":"write","model":"ctrl_neutral1","sid":"158d0001828xxx","short_id":30115,"data":{"channel_0":"off"}}
